version: "3.0"

services:
  app:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./
    working_dir: /var/www/
    networks:
      - laravel-app
    volumes:
      - ./public/:/var/www/public
      - ./storage/:/var/www/storage
    env_file:
      - docker/staging/env
    depends_on:
      - db

  production_webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 2097:80
    volumes:
      - ./public/:/var/www/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel-app

  db:
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      POSTGRES_PASSWORD: teaching_mgmt_bahasa
      POSTGRES_USER: teaching_mgmt
      POSTGRES_DB: teaching_management
      # POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - bd-postgres-data:/var/lib/postgresql/data
    ports:
      - 2075:5432
    networks:
      - laravel-app

networks:
  laravel-app:
    driver: bridge

volumes:
  bd-postgres-data:
# volumes:
#      app-public: ./public:/var/www/public
